# https://phptoday.ru/post/gotovim-lokalnuyu-sredu-docker-dlya-razrabotki-na-php
# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    container_name: nginx
    # используем последний стабильный образ nginx
    image: nginx:latest
    restart: on-failure
    # маршрутизируем порты
    ports:
      - "80:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./../../App:/var/www
      - ./logs:/var/log/nginx
    environment:
      - TZ=Europe/Moscow
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    container_name: php
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./php
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ../../.env
    # монтируем директорию с проектами
    volumes:
      - ./../../App:/var/www
      - ./../../.env:/var/.env
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'Europe/Moscow'
      PGTZ: 'Europe/Moscow'

volumes:
  postgres_database:
    external: false
